name = "PyBoltz"
uuid = "0bca4874-a2b8-4dca-bc03-d2d86e344f1f"
authors = ["Anton Oresten and Aron Stålmarck"]
version = "0.2.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"

[extensions]
BioStructuresExt = "BioStructures"
ProteinChainsExt = "ProteinChains"

[compat]
BioStructures = "4"
Compat = "4.16"
CondaPkg = "0.2"
ProteinChains = "0.7"
PythonCall = "0.9"
Scratch = "1"
YAML = "0.4"
julia = "1.10"
